components:
  schemas:
    AllCaptors:
      properties:
        iata:
          description: Identifiant d'un aeroport
          example: CDG
          type: string
        pressure:
          description: Liste des valeurs pour les capteurs de pression
          example:
          - date: 2022-12-25-12-00-00
            value: "1015.13"
          items:
            properties:
              date:
                description: Date (YYYY-MM-DD-HH-MM-SS) de l'enregistrement de la
                  valeur
                example: 2022-12-25-12-00-00
                type: string
              value:
                description: Valeur enregistré par le capteur
                example: "25.8"
                type: string
            type: object
          type: array
        temperature:
          description: Liste des valeurs pour les capteurs de temperature
          example:
          - date: 2022-12-25-12-00-00
            value: "25.5"
          items:
            $ref: '#/components/schemas/Measure'
          type: array
        wind:
          description: Liste des valeurs pour les capteurs de vitesse du vent
          example:
          - date: 2022-12-25-12-00-00
            value: "60.6"
          items:
            $ref: '#/components/schemas/Measure'
          type: array
      type: object
    BetweenDate:
      properties:
        captorName:
          description: Nom du type du capteur
          example: pressure
          type: string
        end:
          description: Date (YYYY-MM-DD-HH) de la fin de la plage horaire
          example: 2022-12-25-13
          type: string
        start:
          description: Date (YYYY-MM-DD-HH) du début de la plage horaire
          example: 2022-12-25-12
          type: string
        values:
          description: Liste de valeurs associé a un code iata et un type de capteur
            compris dans le plage horaire
          example:
          - date: 2022-12-25-12-00-00
            value: "60.6"
          items:
            $ref: '#/components/schemas/Iata'
          type: array
      type: object
    Captor:
      properties:
        captorName:
          description: Nom du type du capteur
          example: pressure
          type: string
        values:
          description: Liste de code iata et de ses valeurs
          example:
          - iata: CDG
            measures:
            - date: 2022-12-25-12-00-00
              value: "60.6"
          items:
            properties:
              iata:
                description: Identifiant d'un aeroport
                example: CDG
                type: string
              measures:
                description: Liste de valeurs d'un capteur
                example:
                - date: 2022-12-25-12-00-00
                  value: "60.6"
                items:
                  $ref: '#/components/schemas/Measure'
                type: array
            type: object
          type: array
      type: object
    CaptorAndIata:
      properties:
        captorName:
          description: Nom du type du capteur
          example: pressure
          type: string
        iata:
          description: Identifiant d'un aeroport
          example: CDG
          type: string
        values:
          description: Liste de valeurs associé a un code iata et un type de capteur
          example:
          - date: 2022-12-25-12-00-00
            value: "60.6"
          items:
            $ref: '#/components/schemas/Measure'
          type: array
      type: object
    DateAndAllCaptors:
      properties:
        date:
          description: Date (YYYY-MM-DD) du jour ou l'on veut connaitre les moyennes
            des valeurs
          example: "2022-12-25"
          type: string
        pressure:
          description: Valeur moyenne des données de pression
          example: 950.12
          type: number
        temperature:
          description: Valeur moyenne des données de temperature
          example: 25.3
          type: number
        wind:
          description: Valeur moyenne des données de vitesse du vent
          example: 60.2
          type: number
      type: object
    Iata:
      properties:
        iata:
          description: Identifiant d'un aeroport
          example: CDG
          type: string
        measures:
          description: Liste de valeurs d'un capteur
          example:
          - date: 2022-12-25-12-00-00
            value: "60.6"
          items:
            $ref: '#/components/schemas/Measure'
          type: array
      type: object
    Measure:
      properties:
        date:
          description: Date (YYYY-MM-DD-HH-MM-SS) de l'enregistrement de la valeur
          example: 2022-12-25-12-00-00
          type: string
        value:
          description: Valeur enregistré par le capteur
          example: "25.8"
          type: string
      type: object
info:
  description: l'API expose les données générées par nos publishers
  title: API de données de capteurs d'aeroports
  version: 1.0.0
openapi: 3.0.0
paths:
  /averages/{date}:
    get:
      description: ' Obtenir la moyenne de tous les relevés d''un jour donné.'
      parameters:
      - description: Date
        in: path
        name: date
        required: true
        schema:
          description: Date
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DateAndAllCaptors'
          description: CaptorAndIata JSON
      summary: GetAverageByDate
  /iata/{code}:
    get:
      description: ' Obtenir tous les relevés de mesure selon un code iata'
      parameters:
      - description: Code iata
        in: path
        name: code
        required: true
        schema:
          description: Code iata
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllCaptors'
          description: AllCaptors JSON
      summary: GetDataByIataCode
  /iata/{code}/number/{number}:
    get:
      description: ' Obtenir un nombre donné de relevés de mesure selon un code iata'
      parameters:
      - description: Code iata
        in: path
        name: code
        required: true
        schema:
          description: Code iata
          format: string
          type: string
      - description: Nombre
        in: path
        name: number
        required: true
        schema:
          description: Nombre
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllCaptors'
          description: AllCaptors JSON
      summary: GetDataByIataCodeForXData
  /iata/{code}/sensor/{sensorName}:
    get:
      description: ' Obtenir tous les relevés de mesure d''un aeroport et d un seul
        type de capteur.'
      parameters:
      - description: Code iata
        in: path
        name: code
        required: true
        schema:
          description: Code iata
          format: string
          type: string
      - description: Captor name
        in: path
        name: sensorName
        required: true
        schema:
          description: Captor name
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaptorAndIata'
          description: CaptorAndIata JSON
      summary: GetDataByIataCodeAndCaptor
  /sensor/{sensorName}:
    get:
      description: ' Obtenir tous les relevés de mesure d''un type de capteur'
      parameters:
      - description: Captor name
        in: path
        name: sensorName
        required: true
        schema:
          description: Captor name
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Captor'
          description: Captor JSON
      summary: GetDataByCaptor
  /sensor/{sensorName}/between/{start_date}/to/{end_date}:
    get:
      description: ' Obtenir tous les relevés de mesure d un type de capteur dans
        une plage de temps donnée.'
      parameters:
      - description: Captor name
        in: path
        name: sensorName
        required: true
        schema:
          description: Captor name
          format: string
          type: string
      - description: Start
        in: path
        name: start_date
        required: true
        schema:
          description: Start
          format: string
          type: string
      - description: End
        in: path
        name: end_date
        required: true
        schema:
          description: End
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BetweenDate'
          description: CaptorAndIata JSON
      summary: GetDataBetweenDates
servers:
- description: Default Server URL
  url: /
